[versions]
agp = "8.1.0"
kotlin = "1.9.23"

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }