export default {
  // Home Screen
  appTitle: 'طبيب النباتات بالذكاء الاصطناعي',
  appSubtitle: 'تشخيص أمراض النباتات بالذكاء الاصطناعي',
  takePhotoButton: 'التقط صورة وقم بالتشخيص',
  getPremiumButton: 'احصل على بريميوم',

  // Camera Screen
  plantDiagnosisTitle: 'تشخيص أمراض النباتات',
  takePhotoBtn: 'التقط صورة',
  selectGalleryBtn: 'اختر من المعرض',
  analyzePlantBtn: 'تحليل النبات',
  analyzingText: 'جاري التحليل...',
  diagnosisLabel: 'التشخيص:',
  
  // Results Screen
  diagnosisResults: '🩺 نتائج التشخيص',
  saveButton: '💾 حفظ في نباتاتي',
  savedButton: '✅ تم الحفظ',
  shareButton: '📤 مشاركة النتائج',
  generalCareTips: '💡 نصائح عامة للعناية بالنباتات:',
  tip1: '• راقب نباتك يوميًا للتغييرات',
  tip2: '• تأكد من التصريف الجيد في الأصص',
  tip3: '• اضبط الري حسب الموسم',
  tip4: '• وفر إضاءة كافية لنوع نباتك',
  tip5: '• أزل الأوراق الميتة أو المريضة على الفور',
  diagnoseAnotherButton: '📷 تشخيص نبات آخر',
  backHomeButton: '🏠 العودة للرئيسية',
  
  // Premium Screen
  premiumTitle: 'الترقية إلى بريميوم',
  premiumSubtitle: 'احصل على تشخيصات غير محدودة وميزات حصرية',
  basicPlanTitle: 'الخطة الأساسية',
  basicPlanPrice: '4.99 دولار/شهريًا',
  premiumPlanTitle: 'خطة بريميوم',
  premiumPlanPrice: '49.99 دولار/سنويًا',
  premiumSavings: 'وفر 17%!',
  feature1: '✓ تشخيصات نباتات غير محدودة',
  feature2: '✓ خطط علاج مفصلة',
  feature3: '✓ دعم ذو أولوية',
  feature4: '✓ حفظ سجل التشخيصات',
  feature5: '✓ استشارة الخبراء (بريميوم فقط)',
  feature6: '✓ وصول مبكر للميزات الجديدة (بريميوم فقط)',
  subscribeButton: 'اشترك الآن',
  backButton: 'رجوع',
  
  // Profile Screen
  profileTitle: 'ملفي الشخصي',
  freeStatus: 'مجاني',
  premiumStatus: 'بريميوم',
  diagnosesCountLabel: 'التشخيصات',
  savedPlantsLabel: 'النباتات المحفوظة',
  upgradeToPremium: 'الترقية إلى بريميوم',
  upgradeDescription: 'احصل على تشخيصات غير محدودة ووصول إلى ميزات الخبراء',
  upgradeBtn: 'قم بالترقية الآن',
  myPlantsTitle: 'نباتاتي المحفوظة',
  emptyStateIcon: '🌱',
  emptyStateTitle: 'لا توجد نباتات محفوظة بعد',
  emptyStateDescription: 'ابدأ بتشخيص نباتاتك لبناء مجموعتك',
  diagnoseNowButton: 'شخص الآن',
  clearHistoryButton: 'مسح السجل',
  
  // Alerts
  permissionRequired: 'الإذن مطلوب',
  cameraPermission: 'إذن الكاميرا مطلوب لالتقاط صورة.',
  mediaPermission: 'إذن مكتبة الوسائط مطلوب لتحديد صورة.',
  upgradeRequired: 'الترقية مطلوبة',
  freeLimitReached: 'لقد استخدمت جميع التحليلات المجانية الثلاثة. قم بالترقية إلى بريميوم للحصول على تشخيصات غير محدودة.',
  error: 'خطأ',
  selectImageFirst: 'يرجى تحديد صورة أولاً',
  analysisFailed: 'فشل تحليل الصورة. يرجى المحاولة مرة أخرى.',
  confirmDelete: 'تأكيد الحذف',
  deleteMessage: 'هل أنت متأكد من رغبتك في حذف هذا التشخيص؟',
  confirmClear: 'تأكيد المسح',
  clearMessage: 'هل أنت متأكد من رغبتك في مسح جميع التشخيصات المحفوظة؟',
  cancel: 'إلغاء',
  delete: 'حذف',
  clear: 'مسح',
  upgrade: 'ترقية',
  
  // Share Message
  shareTitle: 'تشخيص طبيب النباتات',
  shareMessage: 'تشخيص طبيب النباتات:\n\n{disease}\n\nالعلاج: {treatment}\n\nاحصل على تشخيص مجاني على: timerhaven.com',
};
