export default {
  // Home Screen
  appTitle: 'AI Γιατρός Φυτών',
  appSubtitle: 'Διαγνώστε ασθένειες φυτών με AI',
  takePhotoButton: 'Τραβήξτε φωτογραφία και διαγνώστε',
  getPremiumButton: 'Αποκτήστε Premium',

  // Camera Screen
  plantDiagnosisTitle: 'Διάγνωση ασθενειών φυτών',
  takePhotoBtn: 'Τραβήξτε φωτογραφία',
  selectGalleryBtn: 'Επιλέξτε από τη συλλογή',
  analyzePlantBtn: 'Αναλύστε το φυτό',
  analyzingText: 'Ανάλυση...',
  diagnosisLabel: 'Διάγνωση:',
  
  // Results Screen
  diagnosisResults: '🩺 Αποτελέσματα διάγνωσης',
  saveButton: '💾 Αποθήκευση στα φυτά μου',
  savedButton: '✅ Αποθηκεύτηκε',
  shareButton: '📤 Κοινοποίηση αποτελεσμάτων',
  generalCareTips: '💡 Γενικές συμβουλές φροντίδας φυτών:',
  tip1: '• Παρακολουθείτε το φυτό σας καθημερινά',
  tip2: '• Εξασφαλίστε καλή αποστράγγιση στις γλάστρες',
  tip3: '• Προσαρμόστε το πότισμα ανάλογα με την εποχή',
  tip4: '• Παρέχετε επαρκές φως για τον τύπο του φυτού σας',
  tip5: '• Αφαιρέστε άμεσα τα νεκρά ή άρρωστα φύλλα',
  diagnoseAnotherButton: '📷 Διαγνώστε άλλο φυτό',
  backHomeButton: '🏠 Επιστροφή στην αρχική',
  
  // Premium Screen
  premiumTitle: 'Αναβάθμιση σε Premium',
  premiumSubtitle: 'Αποκτήστε απεριόριστες διαγνώσεις και αποκλειστικές λειτουργίες',
  basicPlanTitle: 'Βασικό Πλάνο',
  basicPlanPrice: '4,99 €/μήνα',
  premiumPlanTitle: 'Premium Πλάνο',
  premiumPlanPrice: '49,99 €/έτος',
  premiumSavings: 'Εξοικονομήστε 17%!',
  feature1: '✓ Απεριόριστες διαγνώσεις φυτών',
  feature2: '✓ Λεπτομερή σχέδια θεραπείας',
  feature3: '✓ Προτεραιότητα υποστήριξης',
  feature4: '✓ Ιστορικό διαγνώσεων',
  feature5: '✓ Συμβουλές ειδικού (μόνο Premium)',
  feature6: '✓ Πρώιμη πρόσβαση σε νέες λειτουργίες (μόνο Premium)',
  subscribeButton: 'Εγγραφή τώρα',
  backButton: 'Πίσω',
  
  // Profile Screen
  profileTitle: 'Το προφίλ μου',
  freeStatus: 'ΔΩΡΕΑΝ',
  premiumStatus: 'PREMIUM',
  diagnosesCountLabel: 'Διαγνώσεις',
  savedPlantsLabel: 'Αποθηκευμένα φυτά',
  upgradeToPremium: 'Αναβάθμιση σε Premium',
  upgradeDescription: 'Αποκτήστε απεριόριστες διαγνώσεις και πρόσβαση σε λειτουργίες ειδικών',
  upgradeBtn: 'Αναβάθμιση τώρα',
  myPlantsTitle: 'Τα αποθηκευμένα φυτά μου',
  emptyStateIcon: '🌱',
  emptyStateTitle: 'Δεν υπάρχουν αποθηκευμένα φυτά ακόμα',
  emptyStateDescription: 'Ξεκινήστε να διαγιγνώσκετε τα φυτά σας για να δημιουργήσετε τη συλλογή σας',
  diagnoseNowButton: 'Διαγνώστε τώρα',
  clearHistoryButton: 'Εκκαθάριση ιστορικού',
  
  // Alerts
  permissionRequired: 'Απαιτείται άδεια',
  cameraPermission: 'Απαιτείται άδεια κάμερας για τη λήψη φωτογραφίας.',
  mediaPermission: 'Απαιτείται άδεια βιβλιοθήκης πολυμέσων για την επιλογή φωτογραφίας.',
  upgradeRequired: 'Απαιτείται αναβάθμιση',
  freeLimitReached: 'Χρησιμοποιήσατε και τις 3 δωρεάν αναλύσεις. Αναβαθμίστε σε Premium για απεριόριστες διαγνώσεις.',
  error: 'Σφάλμα',
  selectImageFirst: 'Παρακαλώ επιλέξτε πρώτα μια εικόνα',
  analysisFailed: 'Αποτυχία ανάλυσης εικόνας. Παρακαλώ δοκιμάστε ξανά.',
  confirmDelete: 'Επιβεβαίωση διαγραφής',
  deleteMessage: 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτή τη διάγνωση;',
  confirmClear: 'Επιβεβαίωση εκκαθάρισης',
  clearMessage: 'Είστε βέβαιοι ότι θέλετε να εκκαθαρίσετε όλες τις αποθηκευμένες διαγνώσεις;',
  cancel: 'Ακύρωση',
  delete: 'Διαγραφή',
  clear: 'Εκκαθάριση',
  upgrade: 'Αναβάθμιση',
  
  // Share Message
  shareTitle: 'Διάγνωση Γιατρού Φυτών',
  shareMessage: 'Διάγνωση Γιατρού Φυτών:\n\n{disease}\n\nΘεραπεία: {treatment}\n\nΑποκτήστε τη δωρεάν διάγνωση στο: timerhaven.com',
};
