export default {
  // Home Screen
  appTitle: 'AI Plant Doctor',
  appSubtitle: 'Diagnose plant diseases with AI',
  takePhotoButton: 'Take Photo & Diagnose',
  getPremiumButton: 'Get Premium',

  // Camera Screen
  plantDiagnosisTitle: 'Plant Disease Diagnosis',
  takePhotoBtn: 'Take Photo',
  selectGalleryBtn: 'Select from Gallery',
  analyzePlantBtn: 'Analyze Plant',
  analyzingText: 'Analyzing...',
  diagnosisLabel: 'Diagnosis:',
  
  // Results Screen
  diagnosisResults: '🩺 Diagnosis Results',
  saveButton: '💾 Save to My Plants',
  savedButton: '✅ Saved',
  shareButton: '📤 Share Results',
  generalCareTips: '💡 General Plant Care Tips:',
  tip1: '• Monitor your plant daily for changes',
  tip2: '• Ensure proper drainage in pots',
  tip3: '• Adjust watering based on season',
  tip4: '• Provide adequate light for your plant type',
  tip5: '• Remove dead or diseased leaves promptly',
  diagnoseAnotherButton: '📷 Diagnose Another Plant',
  backHomeButton: '🏠 Back to Home',
  
  // Premium Screen
  premiumTitle: 'Upgrade to Premium',
  premiumSubtitle: 'Get unlimited plant diagnoses and exclusive features',
  basicPlanTitle: 'Basic Plan',
  basicPlanPrice: '$4.99/month',
  premiumPlanTitle: 'Premium Plan',
  premiumPlanPrice: '$49.99/year',
  premiumSavings: 'Save 17%!',
  feature1: '✓ Unlimited plant diagnoses',
  feature2: '✓ Detailed treatment plans',
  feature3: '✓ Priority support',
  feature4: '✓ Save diagnosis history',
  feature5: '✓ Expert consultation (Premium only)',
  feature6: '✓ Early access to new features (Premium only)',
  subscribeButton: 'Subscribe Now',
  backButton: 'Back',
  
  // Profile Screen
  profileTitle: 'My Profile',
  freeStatus: 'FREE',
  premiumStatus: 'PREMIUM',
  diagnosesCountLabel: 'Diagnoses',
  savedPlantsLabel: 'Saved Plants',
  upgradeToPremium: 'Upgrade to Premium',
  upgradeDescription: 'Get unlimited diagnoses and access to expert features',
  upgradeBtn: 'Upgrade Now',
  myPlantsTitle: 'My Saved Plants',
  emptyStateIcon: '🌱',
  emptyStateTitle: 'No Saved Plants Yet',
  emptyStateDescription: 'Start diagnosing your plants to build your collection',
  diagnoseNowButton: 'Diagnose Now',
  clearHistoryButton: 'Clear History',
  
  // Alerts
  permissionRequired: 'Permission required',
  cameraPermission: 'Camera permission is required to take a photo.',
  mediaPermission: 'Media library permission is required to select a photo.',
  upgradeRequired: 'Upgrade Required',
  freeLimitReached: 'You have used all 3 free analyses. Upgrade to Premium for unlimited diagnoses.',
  error: 'Error',
  selectImageFirst: 'Please select an image first',
  analysisFailed: 'Failed to analyze image. Please try again.',
  confirmDelete: 'Confirm Delete',
  deleteMessage: 'Are you sure you want to delete this diagnosis?',
  confirmClear: 'Confirm Clear',
  clearMessage: 'Are you sure you want to clear all saved diagnoses?',
  cancel: 'Cancel',
  delete: 'Delete',
  clear: 'Clear',
  upgrade: 'Upgrade',
  
  // Share Message
  shareTitle: 'Plant Doctor Diagnosis',
  shareMessage: 'Plant Doctor Diagnosis:\n\n{disease}\n\nTreatment: {treatment}\n\nGet your free plant diagnosis at: timerhaven.com',
};
