export default {
  // Home Screen
  appTitle: 'Doctor de Plantas IA',
  appSubtitle: 'Diagnostica enfermedades de plantas con IA',
  takePhotoButton: 'Tomar foto y diagnosticar',
  getPremiumButton: 'Obtener Premium',

  // Camera Screen
  plantDiagnosisTitle: 'Diagnóstico de enfermedades de plantas',
  takePhotoBtn: 'Tomar foto',
  selectGalleryBtn: 'Seleccionar de la galería',
  analyzePlantBtn: 'Analizar planta',
  analyzingText: 'Analizando...',
  diagnosisLabel: 'Diagnóstico:',
  
  // Results Screen
  diagnosisResults: '🩺 Resultados del diagnóstico',
  saveButton: '💾 Guardar en mis plantas',
  savedButton: '✅ Guardado',
  shareButton: '📤 Compartir resultados',
  generalCareTips: '💡 Consejos generales de cuidado de plantas:',
  tip1: '• Monitorea tu planta diariamente',
  tip2: '• Asegura un buen drenaje en las macetas',
  tip3: '• Ajusta el riego según la temporada',
  tip4: '• Proporciona luz adecuada para tu tipo de planta',
  tip5: '• Retira hojas muertas o enfermas rápidamente',
  diagnoseAnotherButton: '📷 Diagnosticar otra planta',
  backHomeButton: '🏠 Volver al inicio',
  
  // Premium Screen
  premiumTitle: 'Actualizar a Premium',
  premiumSubtitle: 'Obtén diagnósticos ilimitados y funciones exclusivas',
  basicPlanTitle: 'Plan Básico',
  basicPlanPrice: '$4.99/mes',
  premiumPlanTitle: 'Plan Premium',
  premiumPlanPrice: '$49.99/año',
  premiumSavings: '¡Ahorra 17%!',
  feature1: '✓ Diagnósticos de plantas ilimitados',
  feature2: '✓ Planes de tratamiento detallados',
  feature3: '✓ Soporte prioritario',
  feature4: '✓ Historial de diagnósticos',
  feature5: '✓ Consulta de expertos (Solo Premium)',
  feature6: '✓ Acceso anticipado a nuevas funciones (Solo Premium)',
  subscribeButton: 'Suscribirse ahora',
  backButton: 'Atrás',
  
  // Profile Screen
  profileTitle: 'Mi Perfil',
  freeStatus: 'GRATIS',
  premiumStatus: 'PREMIUM',
  diagnosesCountLabel: 'Diagnósticos',
  savedPlantsLabel: 'Plantas guardadas',
  upgradeToPremium: 'Actualizar a Premium',
  upgradeDescription: 'Obtén diagnósticos ilimitados y acceso a funciones de experto',
  upgradeBtn: 'Actualizar ahora',
  myPlantsTitle: 'Mis plantas guardadas',
  emptyStateIcon: '🌱',
  emptyStateTitle: 'Aún no hay plantas guardadas',
  emptyStateDescription: 'Comienza a diagnosticar tus plantas para crear tu colección',
  diagnoseNowButton: 'Diagnosticar ahora',
  clearHistoryButton: 'Limpiar historial',
  
  // Alerts
  permissionRequired: 'Permiso requerido',
  cameraPermission: 'Se requiere permiso de cámara para tomar una foto.',
  mediaPermission: 'Se requiere permiso de biblioteca multimedia para seleccionar una foto.',
  upgradeRequired: 'Actualización requerida',
  freeLimitReached: 'Has usado los 3 análisis gratuitos. Actualiza a Premium para diagnósticos ilimitados.',
  error: 'Error',
  selectImageFirst: 'Por favor selecciona una imagen primero',
  analysisFailed: 'Error al analizar la imagen. Por favor intenta de nuevo.',
  confirmDelete: 'Confirmar eliminación',
  deleteMessage: '¿Estás seguro de que quieres eliminar este diagnóstico?',
  confirmClear: 'Confirmar limpieza',
  clearMessage: '¿Estás seguro de que quieres limpiar todos los diagnósticos guardados?',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  clear: 'Limpiar',
  upgrade: 'Actualizar',
  
  // Share Message
  shareTitle: 'Diagnóstico Doctor de Plantas',
  shareMessage: 'Diagnóstico Doctor de Plantas:\n\n{disease}\n\nTratamiento: {treatment}\n\nObtén tu diagnóstico gratuito en: timerhaven.com',
};
