export default {
  // Home Screen
  appTitle: 'Docteur des Plantes IA',
  appSubtitle: 'Diagnostiquer les maladies des plantes avec l\'IA',
  takePhotoButton: 'Prendre une photo et diagnostiquer',
  getPremiumButton: 'Obtenir Premium',

  // Camera Screen
  plantDiagnosisTitle: 'Diagnostic des maladies des plantes',
  takePhotoBtn: 'Prendre une photo',
  selectGalleryBtn: 'Sélectionner depuis la galerie',
  analyzePlantBtn: 'Analyser la plante',
  analyzingText: 'Analyse en cours...',
  diagnosisLabel: 'Diagnostic:',
  
  // Results Screen
  diagnosisResults: '🩺 Résultats du diagnostic',
  saveButton: '💾 Enregistrer dans mes plantes',
  savedButton: '✅ Enregistré',
  shareButton: '📤 Partager les résultats',
  generalCareTips: '💡 Conseils généraux d\'entretien des plantes:',
  tip1: '• Surveillez votre plante quotidiennement',
  tip2: '• Assurez un bon drainage dans les pots',
  tip3: '• Ajustez l\'arrosage selon la saison',
  tip4: '• Fournissez une lumière adéquate pour votre type de plante',
  tip5: '• Retirez rapidement les feuilles mortes ou malades',
  diagnoseAnotherButton: '📷 Diagnostiquer une autre plante',
  backHomeButton: '🏠 Retour à l\'accueil',
  
  // Premium Screen
  premiumTitle: 'Passer à Premium',
  premiumSubtitle: 'Obtenez des diagnostics illimités et des fonctionnalités exclusives',
  basicPlanTitle: 'Plan Basique',
  basicPlanPrice: '4,99 €/mois',
  premiumPlanTitle: 'Plan Premium',
  premiumPlanPrice: '49,99 €/an',
  premiumSavings: 'Économisez 17%!',
  feature1: '✓ Diagnostics de plantes illimités',
  feature2: '✓ Plans de traitement détaillés',
  feature3: '✓ Support prioritaire',
  feature4: '✓ Historique des diagnostics',
  feature5: '✓ Consultation d\'expert (Premium uniquement)',
  feature6: '✓ Accès anticipé aux nouvelles fonctionnalités (Premium uniquement)',
  subscribeButton: 'S\'abonner maintenant',
  backButton: 'Retour',
  
  // Profile Screen
  profileTitle: 'Mon Profil',
  freeStatus: 'GRATUIT',
  premiumStatus: 'PREMIUM',
  diagnosesCountLabel: 'Diagnostics',
  savedPlantsLabel: 'Plantes enregistrées',
  upgradeToPremium: 'Passer à Premium',
  upgradeDescription: 'Obtenez des diagnostics illimités et accédez aux fonctionnalités d\'expert',
  upgradeBtn: 'Mettre à niveau maintenant',
  myPlantsTitle: 'Mes plantes enregistrées',
  emptyStateIcon: '🌱',
  emptyStateTitle: 'Aucune plante enregistrée',
  emptyStateDescription: 'Commencez à diagnostiquer vos plantes pour créer votre collection',
  diagnoseNowButton: 'Diagnostiquer maintenant',
  clearHistoryButton: 'Effacer l\'historique',
  
  // Alerts
  permissionRequired: 'Permission requise',
  cameraPermission: 'La permission de la caméra est requise pour prendre une photo.',
  mediaPermission: 'La permission de la bibliothèque multimédia est requise pour sélectionner une photo.',
  upgradeRequired: 'Mise à niveau requise',
  freeLimitReached: 'Vous avez utilisé les 3 analyses gratuites. Passez à Premium pour des diagnostics illimités.',
  error: 'Erreur',
  selectImageFirst: 'Veuillez d\'abord sélectionner une image',
  analysisFailed: 'Échec de l\'analyse de l\'image. Veuillez réessayer.',
  confirmDelete: 'Confirmer la suppression',
  deleteMessage: 'Êtes-vous sûr de vouloir supprimer ce diagnostic?',
  confirmClear: 'Confirmer l\'effacement',
  clearMessage: 'Êtes-vous sûr de vouloir effacer tous les diagnostics enregistrés?',
  cancel: 'Annuler',
  delete: 'Supprimer',
  clear: 'Effacer',
  upgrade: 'Mettre à niveau',
  
  // Share Message
  shareTitle: 'Diagnostic Docteur des Plantes',
  shareMessage: 'Diagnostic Docteur des Plantes:\n\n{disease}\n\nTraitement: {treatment}\n\nObtenez votre diagnostic gratuit sur: timerhaven.com',
};
