export default {
  // Home Screen
  appTitle: 'AI Доктор Растений',
  appSubtitle: 'Диагностика болезней растений с помощью ИИ',
  takePhotoButton: 'Сделать фото и диагностировать',
  getPremiumButton: 'Получить Premium',

  // Camera Screen
  plantDiagnosisTitle: 'Диагностика болезней растений',
  takePhotoBtn: 'Сделать фото',
  selectGalleryBtn: 'Выбрать из галереи',
  analyzePlantBtn: 'Анализировать растение',
  analyzingText: 'Анализируем...',
  diagnosisLabel: 'Диагноз:',
  
  // Results Screen
  diagnosisResults: '🩺 Результаты диагностики',
  saveButton: '💾 Сохранить в мои растения',
  savedButton: '✅ Сохранено',
  shareButton: '📤 Поделиться результатами',
  generalCareTips: '💡 Общие советы по уходу за растениями:',
  tip1: '• Наблюдайте за растением ежедневно',
  tip2: '• Обеспечьте хороший дренаж в горшках',
  tip3: '• Регулируйте полив в зависимости от сезона',
  tip4: '• Обеспечьте достаточное освещение для вашего типа растения',
  tip5: '• Своевременно удаляйте мертвые или больные листья',
  diagnoseAnotherButton: '📷 Диагностировать другое растение',
  backHomeButton: '🏠 Вернуться домой',
  
  // Premium Screen
  premiumTitle: 'Перейти на Premium',
  premiumSubtitle: 'Получите неограниченные диагнозы и эксклюзивные функции',
  basicPlanTitle: 'Базовый план',
  basicPlanPrice: '499 ₽/месяц',
  premiumPlanTitle: 'Premium план',
  premiumPlanPrice: '4999 ₽/год',
  premiumSavings: 'Экономия 17%!',
  feature1: '✓ Неограниченные диагнозы растений',
  feature2: '✓ Подробные планы лечения',
  feature3: '✓ Приоритетная поддержка',
  feature4: '✓ История диагнозов',
  feature5: '✓ Консультация эксперта (только Premium)',
  feature6: '✓ Ранний доступ к новым функциям (только Premium)',
  subscribeButton: 'Подписаться сейчас',
  backButton: 'Назад',
  
  // Profile Screen
  profileTitle: 'Мой профиль',
  freeStatus: 'БЕСПЛАТНО',
  premiumStatus: 'PREMIUM',
  diagnosesCountLabel: 'Диагнозы',
  savedPlantsLabel: 'Сохраненные растения',
  upgradeToPremium: 'Перейти на Premium',
  upgradeDescription: 'Получите неограниченные диагнозы и доступ к экспертным функциям',
  upgradeBtn: 'Обновить сейчас',
  myPlantsTitle: 'Мои сохраненные растения',
  emptyStateIcon: '🌱',
  emptyStateTitle: 'Нет сохраненных растений',
  emptyStateDescription: 'Начните диагностировать растения, чтобы создать свою коллекцию',
  diagnoseNowButton: 'Диагностировать сейчас',
  clearHistoryButton: 'Очистить историю',
  
  // Alerts
  permissionRequired: 'Требуется разрешение',
  cameraPermission: 'Требуется разрешение камеры для съемки фото.',
  mediaPermission: 'Требуется разрешение медиатеки для выбора фото.',
  upgradeRequired: 'Требуется обновление',
  freeLimitReached: 'Вы использовали все 3 бесплатных анализа. Перейдите на Premium для неограниченных диагнозов.',
  error: 'Ошибка',
  selectImageFirst: 'Пожалуйста, сначала выберите изображение',
  analysisFailed: 'Не удалось проанализировать изображение. Пожалуйста, попробуйте снова.',
  confirmDelete: 'Подтвердить удаление',
  deleteMessage: 'Вы уверены, что хотите удалить этот диагноз?',
  confirmClear: 'Подтвердить очистку',
  clearMessage: 'Вы уверены, что хотите очистить все сохраненные диагнозы?',
  cancel: 'Отмена',
  delete: 'Удалить',
  clear: 'Очистить',
  upgrade: 'Обновить',
  
  // Share Message
  shareTitle: 'Диагноз Доктора Растений',
  shareMessage: 'Диагноз Доктора Растений:\n\n{disease}\n\nЛечение: {treatment}\n\nПолучите бесплатную диагностику на: timerhaven.com',
};
